# Generated by Django 4.2.1 on 2023-05-29 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_extra_alter_blog_fecha_alter_blog_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 28, 20, 50, 53, 554517)),
        ),
    ]
